[package]
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
name = "chapter-nine"
version = "0.1.0"
edition = "2024"
[dependencies]
cfg-if = "=0.1.10"
futures = "0.1.31"
hyper = "0.12.36"
reqwest = { version = "0.9.24", default-features = false, features = ["rustls-tls"] }
serde = "1.0.229"
serde_derive = "1.0.229"
